export const commonRoutes = [
  {
    path: "/user/hospital/internal-user/dashboard",
    title: "Dashboard",
    iconType: "material-icons-two-tone",
    icon: "dashboard",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  // {
  //   path: "/user/hospital/internal-user/analytics-dashboard",
  //   title: "Analytics Dashboard",
  //   iconType: "material-icons-two-tone",
  //   icon: "bar_chart",
  //   class: "",
  //   groupTitle: false,
  //   active: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [],
  // },
  {
    path: "/user/hospital/internal-user/user",
    title: "Internal User",
    iconType: "material-icons-two-tone",
    icon: "person_add",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/doctor",
    title: "Doctors",
    iconType: "material-icons-two-tone",
    icon: "vaccines",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/hospital",
    title: "Hospital",
    iconType: "material-icons-two-tone",
    icon: "local_hospital",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/patient",
    title: "Patient",
    iconType: "material-icons-two-tone",
    icon: "personal_injury",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/query-management",
    title: "Query Management",
    iconType: "material-icons-two-tone",
    icon: "emergency",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/operation-board",
    title: "Operation Board",
    iconType: "material-icons-two-tone",
    icon: "developer_board",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/email-fetch",
    title: "Email Fetch",
    iconType: "material-icons-two-tone",
    icon: "email",
    class: "",
    groupTitle: false,
    active: false,
    badge: "0",
    badgeClass: "badge customBlueBadgeColor sidebar-badge float-end",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/message-fetch",
    title: "Message Fetch",
    iconType: "material-icons-two-tone",
    icon: "chat",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "badge customBlueBadgeColor sidebar-badge float-end",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/issued-vil",
    title: "Issued VIL",
    iconType: "material-icons-two-tone",
    icon: "article",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/sent-vil-history",
    title: "Sent VIL History",
    iconType: "material-icons-two-tone",
    icon: "history",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/calendar",
    title: "Calendar",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/report",
    title: "Report",
    iconType: "material-icons-two-tone",
    icon: "description",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/hospital-staff",
    title: "Hospital Staff",
    iconType: "material-icons-two-tone",
    icon: "badge",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/doctor-staff",
    title: "Doctor Staff",
    iconType: "material-icons-two-tone",
    icon: "contact_mail",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/treatment-package",
    title: "Treatment Package",
    iconType: "material-icons-two-tone",
    icon: "list_alt",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  // {
  //   path: "",
  //   title: "Doctor Email",
  //   iconType: "material-icons-two-tone",
  //   icon: "contact_mail",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   active: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [
  //     {
  //       path: "/user/hospital/internal-user/doctor-email/doctor-staff",
  //       title: "Doctor Staff",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       active: false,
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //     {
  //       path: "/user/hospital/internal-user/doctor-email/doctor-email-zone",
  //       title: "Doctor Email Zone",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       active: false,
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       submenu: [],
  //     },
  //   ],
  // },
  {
    path: "/user/hospital/internal-user/user-permission",
    title: "User Permission",
    iconType: "material-icons-two-tone",
    icon: "admin_panel_settings",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/error-log",
    title: "Error Log",
    iconType: "material-icons-two-tone",
    icon: "assignment_late",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
];

export const commonAccountRoutes = [
  {
    path: "/user/hospital/internal-user/account/account-details",
    title: "Account Details",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/bank-details",
    title: "Bank Details",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/vil-setting",
    title: "VIL Setting",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/acknowledgement-setting",
    title: "Acknowledgement Setting",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/followup-setting",
    title: "Follow Up Setting",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/template-setting",
    title: "Template Setting",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/email-fetch-setting",
    title: "Email Fetch Setting",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  // {
  //   path: "/user/hospital/internal-user/account/email-setting",
  //   title: "Email Setting",
  //   iconType: "",
  //   icon: "",
  //   class: "ml-menu",
  //   active: false,
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   submenu: [],
  // },
  {
    path: "",
    title: "Email Communication",
    iconType: "",
    icon: "",
    class: "ml-sub-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "/user/hospital/internal-user/account/email-communication/email-host",
        title: "Email Host",
        iconType: "",
        icon: "",
        class: "ml-menu2",
        active: false,
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/user/hospital/internal-user/account/email-communication/default-email",
        title: "Default Email",
        iconType: "",
        icon: "",
        class: "ml-menu2",
        active: false,
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Message Communication",
    iconType: "",
    icon: "",
    class: "ml-sub-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "/user/hospital/internal-user/account/message-communication/message-host",
        title: "Message Host",
        iconType: "",
        icon: "",
        class: "ml-menu2",
        active: false,
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/user/hospital/internal-user/account/message-communication/default-message",
        title: "Default Message",
        iconType: "",
        icon: "",
        class: "ml-menu2",
        active: false,
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
    ],
  },
  {
    path: "/user/hospital/internal-user/account/query-view-setting",
    title: "Query View Setting",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/email-send-setting",
    title: "Email Send Setting",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/message-send-setting",
    title: "Message Send Setting",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/comment-setting",
    title: "Comment Setting",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/communication-setting",
    title: "Communication Setting",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/notification-setting",
    title: "Notification Setting",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/email-content",
    title: "Email Content",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/message-content",
    title: "Message Content",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/hospital-communication",
    title: "Hospital Communication",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/doctor-communication",
    title: "Doctor Communication",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "",
    title: "Partner Communication",
    iconType: "",
    icon: "",
    class: "ml-sub-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "/user/hospital/internal-user/account/referral-partner-communication/pre-staff",
        title: "Pre Staff",
        iconType: "",
        icon: "",
        class: "ml-menu2",
        active: false,
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/user/hospital/internal-user/account/referral-partner-communication/pre-zone",
        title: "Pre Zone",
        iconType: "",
        icon: "",
        class: "ml-menu2",
        active: false,
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/user/hospital/internal-user/account/referral-partner-communication/own-staff",
        title: "Own Staff",
        iconType: "",
        icon: "",
        class: "ml-menu2",
        active: false,
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/user/hospital/internal-user/account/referral-partner-communication/own-zone",
        title: "Own Zone",
        iconType: "",
        icon: "",
        class: "ml-menu2",
        active: false,
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
    ],
  },
  {
    path: "/user/hospital/internal-user/account/top-hospital",
    title: "Top Hospital",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/user-profile",
    title: "User Profile",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/account/change-password",
    title: "Change Password",
    iconType: "",
    icon: "",
    class: "ml-menu",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
];

export const routeForReferral = [
  ...commonRoutes,
  {
    path: "",
    title: "Account Settings",
    iconType: "material-icons-two-tone",
    icon: "settings_suggest",
    class: "menu-toggle",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "/user/hospital/internal-user/account/referral-partner-details",
        title: "Referral Partner Details",
        iconType: "",
        icon: "",
        class: "ml-menu",
        active: false,
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      ...commonAccountRoutes,
    ],
  },
];

export const routeForBranchOffice = [
  ...commonRoutes,
  {
    path: "",
    title: "Account Settings",
    iconType: "material-icons-two-tone",
    icon: "settings_suggest",
    class: "menu-toggle",
    active: false,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "/user/hospital/internal-user/account/branch-office-details",
        title: "Branch Office Details",
        iconType: "",
        icon: "",
        class: "ml-menu",
        active: false,
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      ...commonAccountRoutes,
    ],
  },
];

export const routeForDoctor = [
  {
    path: "/user/hospital/internal-user/dashboard",
    title: "Dashboard",
    iconType: "material-icons-two-tone",
    icon: "dashboard",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/user/hospital/internal-user/query-management",
    title: "Query Management",
    iconType: "material-icons-two-tone",
    icon: "emergency",
    class: "",
    groupTitle: false,
    active: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
];
